### ISSUE TITLE
Exception in thread "AISTPool-6"

### ISSUE THREAD

**Issue by dEROZA** [L2J/L2J_Server#130]
Exception in thread "AISTPool-6" java.lang.NullPointerException
        at com.l2jserver.gameserver.model.zone.type.L2EffectZone.getSkillLevel(L2EffectZone.java:236)
        at ai.group_template.DenOfEvil$KashaDestruction.run(DenOfEvil.java:190)
        at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by Zealar** [comment]
Is still happen?
