### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Sacrifice78** [L2J/L2J_Server#150]
com.l2jserver.gameserver.model.skills.Skill getTargetList
ADVERTENCIA: Exception in L2Skill.getTargetList(): null
java.lang.NullPointerException

**Comment by luksdlt92** [comment]
Please, post all the stack. How we can reproduce it?

**Comment by Sacrifice78** [comment]
Probably could be anything relaccionated with that

com.l2jserver.gameserver.model.skills.Skill getTargetList
ADVERTENCIA: Exception in L2Skill.getTargetList(): null
java.lang.NullPointerException
	at com.l2jserver.gameserver.GeoData.canSeeTarget(GeoData.java:231)
	at handlers.targethandlers.AreaFriendly.checkTarget(AreaFriendly.java:105)
	at handlers.targethandlers.AreaFriendly.getTargetList(AreaFriendly.java:49)
	at com.l2jserver.gameserver.model.skills.Skill.getTargetList(Skill.java:1105)
	at com.l2jserver.gameserver.model.skills.Skill.getTargetList(Skill.java:1074)
	at com.l2jserver.gameserver.model.skills.Skill.getFirstOfTargetList(Skill.java:1123)
	at com.l2jserver.gameserver.model.actor.instance.L2PcInstance.useMagic(L2PcInstance.java:8452)
	at com.l2jserver.gameserver.network.clientpackets.RequestMagicSkillUse.runImpl(RequestMagicSkillUse.java:119)
	at com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:69)
	at com.l2jserver.gameserver.network.L2GameClient.run(L2GameClient.java:1134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by luksdlt92** [comment]
Well, seems equal to https://github.com/L2J/L2J_Server/issues/145

**Comment by Sacrifice78** [comment]
Yes. True.

**Comment by luksdlt92** [comment]
@Zealar Why you closed the issue?

**Comment by Sacrifice78** [comment]
Here we have the reason... +1 @Zealar
