### ISSUE TITLE
IllegalMonitorStateException

### ISSUE THREAD

**Issue by ghost** [L2J/L2J_Server#153]
com.l2jserver.gameserver.ai.L2AttackableAI onEvtThink
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Tyrannosaurus(22215)[268452549] - onEvtThink() failed!
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1137)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1295)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:283)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onIntentionAttack(L2AttackableAI.java:431)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtAttacked(L2AttackableAI.java:2603)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:348)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:327)
	at com.l2jserver.gameserver.model.actor.L2Character.onHitTimer(L2Character.java:4935)
	at com.l2jserver.gameserver.model.actor.tasks.character.HitTask.run(HitTask.java:60)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Zoey76** [comment]
@Sacrifice78 why have you closed this issue?

**Comment by Sacrifice78** [comment]
@Zoey76  I'm re-opened again, please take a look, because happend any time... depending of mob and depending player attacks or be attacked.

**Comment by Sacrifice78** [comment]
com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket run
GRAVE: Client: [Character: xxxx[yyyy] - Account: zzzz - IP: a.b.c.d] - Failed running: [C] 1F Action ; null
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1137)
	at com.l2jserver.gameserver.model.actor.instance.L2PcInstance.doAttack(L2PcInstance.java:4612)
	at com.l2jserver.gameserver.ai.L2PlayerAI.thinkAttack(L2PlayerAI.java:249)
	at com.l2jserver.gameserver.ai.L2PlayerAI.onEvtThink(L2PlayerAI.java:344)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:302)
	at com.l2jserver.gameserver.ai.L2PlayableAI.onIntentionAttack(L2PlayableAI.java:81)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at handlers.actionhandlers.L2NpcAction.action(L2NpcAction.java:87)
	at com.l2jserver.gameserver.model.L2Object.onAction(L2Object.java:128)
	at com.l2jserver.gameserver.model.L2Object.onAction(L2Object.java:120)
	at com.l2jserver.gameserver.network.clientpackets.Action.runImpl(Action.java:150)
	at com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:69)
	at com.l2jserver.gameserver.network.L2GameClient.run(L2GameClient.java:1134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
com.l2jserver.gameserver.ai.L2AttackableAI onEvtThink
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Shaman of Ancient Times(20972)[268527208] - onEvtThink() failed!
java.lang.NullPointerException
	at com.l2jserver.gameserver.model.actor.L2Character.doAttackHitByPole(L2Character.java:1442)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1056)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1295)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onEvtReadyToAct(L2CharacterAI.java:711)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:377)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.model.actor.tasks.character.NotifyAITask.run(NotifyAITask.java:44)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by maneco2** [comment]
Is corfirmed, appened to me too:
https://cdn.pbrd.co/images/vCBjNwp.png

**Comment by Sacrifice78** [comment]
ene 09, 2016 3:06:03 PM com.l2jserver.gameserver.ai.L2AttackableAI onEvtThink
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Soldier of Ancient Times(20970)[268510082] - onEvtThink() for AI_INTENTION_ATTACK failed!
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1140)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1295)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:283)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onIntentionAttack(L2AttackableAI.java:431)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at com.l2jserver.gameserver.model.events.AbstractScript.addAttackPlayerDesire(AbstractScript.java:3186)
	at com.l2jserver.gameserver.model.events.AbstractScript.addAttackPlayerDesire(AbstractScript.java:3170)
	at ai.group_template.SilentValley.onAttack(SilentValley.java:132)
	at com.l2jserver.gameserver.model.quest.Quest.onAttack(Quest.java:1000)
	at com.l2jserver.gameserver.model.quest.Quest.notifyAttack(Quest.java:416)
	at com.l2jserver.gameserver.model.quest.Quest.lambda$addAttackId$52(Quest.java:1914)
	at com.l2jserver.gameserver.model.events.listeners.ConsumerEventListener.executeEvent(ConsumerEventListener.java:46)
	at com.l2jserver.gameserver.model.events.EventDispatcher.notifyToListeners(EventDispatcher.java:242)
	at com.l2jserver.gameserver.model.events.EventDispatcher.notifyEventToMultipleContainers(EventDispatcher.java:178)
	at com.l2jserver.gameserver.model.events.EventDispatcher.lambda$notifyEventAsync$230(EventDispatcher.java:121)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
ene 09, 2016 4:32:32 AM com.l2jserver.gameserver.ai.L2AttackableAI onEvtThink
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Tyrannosaurus(22215)[268452641] - onEvtThink() for AI_INTENTION_ATTACK failed!
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1140)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1295)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:283)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onIntentionAttack(L2AttackableAI.java:431)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtAttacked(L2AttackableAI.java:2603)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:348)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:327)
	at com.l2jserver.gameserver.model.actor.L2Character.onHitTimer(L2Character.java:4938)
	at com.l2jserver.gameserver.model.actor.tasks.character.HitTask.run(HitTask.java:60)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
ene 10, 2016 1:48:17 PM com.l2jserver.gameserver.ai.L2AttackableAI onEvtThink
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Solina Knights(18909)[268467279] - onEvtThink() for AI_INTENTION_ATTACK failed!
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1140)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1295)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:302)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onIntentionAttack(L2AttackableAI.java:431)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at ai.group_template.MonasteryOfSilence.onAdvEvent(MonasteryOfSilence.java:108)
	at com.l2jserver.gameserver.model.quest.Quest.notifyEvent(Quest.java:553)
	at com.l2jserver.gameserver.model.quest.QuestTimer$ScheduleTimerTask.run(QuestTimer.java:49)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
ene 10, 2016 2:57:41 PM com.l2jserver.gameserver.ai.L2AttackableAI onEvtThink
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Lith Commander(21174)[268459028] - onEvtThink() for AI_INTENTION_ATTACK failed!
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1140)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1295)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:283)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onIntentionAttack(L2AttackableAI.java:431)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtAttacked(L2AttackableAI.java:2603)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:348)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:327)
	at com.l2jserver.gameserver.model.actor.L2Character.onHitTimer(L2Character.java:4938)
	at com.l2jserver.gameserver.model.actor.tasks.character.HitTask.run(HitTask.java:60)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
ene 10, 2016 4:21:48 PM com.l2jserver.gameserver.ai.L2AttackableAI onEvtThink
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Changed Creation(20966)[268508656] - onEvtThink() for AI_INTENTION_ATTACK failed!
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1140)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1295)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:283)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onIntentionAttack(L2AttackableAI.java:431)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtAttacked(L2AttackableAI.java:2603)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:348)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:327)
	at com.l2jserver.gameserver.model.actor.L2Character.onHitTimer(L2Character.java:4938)
	at com.l2jserver.gameserver.model.actor.tasks.character.HitTask.run(HitTask.java:60)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Zealar** [comment]
Fixed https://github.com/L2J/L2J_Server/commit/c1683a932cfb6021c51340482c3946dbf6f58492
