### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Sacrifice78** [L2J/L2J_Server#162]
com.l2jserver.gameserver.ai.L2AttackableAI onEvtThink
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Shaman of Ancient Times(20972)[268527208] - onEvtThink() failed!
java.lang.NullPointerException
	at com.l2jserver.gameserver.model.actor.L2Character.doAttackHitByPole(L2Character.java:1442)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1056)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1295)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onEvtReadyToAct(L2CharacterAI.java:711)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:377)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.model.actor.tasks.character.NotifyAITask.run(NotifyAITask.java:44)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by maneco2** [comment]
Same? http://www.l2jserver.com/forum/viewtopic.php?f=77&t=31265

**Comment by Zealar** [comment]
Put that and show logs https://github.com/L2J/L2J_Server/commit/7bcb777a0e9ffc5a060a62d29a440f617179c7a0
