### ISSUE TITLE
Manor NPE

### ISSUE THREAD

**Issue by irlex** [L2J/L2J_Server#181]
com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket run
SEVERE: Client: [Character: .... - Account: ....] - Failed running: [C] 19 UseItem ; null
java.lang.NullPointerException
	at handlers.itemhandlers.Seed.useItem(Seed.java:55)
	at com.l2jserver.gameserver.network.clientpackets.UseItem.runImpl(UseItem.java:356)
	at com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:69)
	at com.l2jserver.gameserver.network.L2GameClient.run(L2GameClient.java:1134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Zealar** [comment]
Fixed https://github.com/L2J/L2J_DataPack/commit/4551b1f6d452492bf6b1a00ac59e804c1bbf255b
