### ISSUE TITLE
AI_INTENTION_ATTACK Problem

### ISSUE THREAD

**Issue by ovalefor** [L2J/L2J_Server#200]
this messages appear frequently on logger.

27/12 13:36:40] L2AttackableAI: Actor: L2MonsterInstance:Tyrannosaurus(22215)[2
68452482] - onEvtThink() for AI_INTENTION_ATTACK failed!
java.lang.IllegalMonitorStateException
        at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
        at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character
.java:1137)
        at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI
.java:1295)
        at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.
java:2545)
        at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:34
5)
        at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:31
6)
        at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2Charact
erAI.java:283)
        at com.l2jserver.gameserver.ai.L2AttackableAI.onIntentionAttack(L2Attack
ableAI.java:431)
        at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:2
82)
        at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:2
57)
        at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtAttacked(L2Attackable
AI.java:2603)
        at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:34
8)
        at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:32
7)
        at com.l2jserver.gameserver.model.actor.L2Character.onHitTimer(L2Charact
er.java:4935)
        at com.l2jserver.gameserver.model.actor.tasks.character.HitTask.run(HitT
ask.java:60)
        at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(Thread
PoolManager.java:89)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by maneco2** [comment]
Original topic: http://www.l2jserver.com/forum/viewtopic.php?f=77&t=31265

**Comment by Sacrifice78** [comment]
ene 10, 2016 12:11:07 PM com.l2jserver.gameserver.ai.L2AttackableAI onEvtThink
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Changed Creation(20966)[268599095] - onEvtThink() for AI_INTENTION_ATTACK failed!
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1140)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1295)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:283)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onIntentionAttack(L2AttackableAI.java:431)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtAttacked(L2AttackableAI.java:2599)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:348)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:327)
	at com.l2jserver.gameserver.model.actor.L2Attackable.addDamage(L2Attackable.java:666)
	at com.l2jserver.gameserver.model.actor.L2Attackable.reduceCurrentHp(L2Attackable.java:290)
	at com.l2jserver.gameserver.model.actor.L2Attackable.reduceCurrentHp(L2Attackable.java:243)
	at com.l2jserver.gameserver.model.actor.L2Character.onHitTimer(L2Character.java:4884)
	at com.l2jserver.gameserver.model.actor.tasks.character.HitTask.run(HitTask.java:60)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
ene 10, 2016 12:11:39 PM com.l2jserver.gameserver.ai.L2AttackableAI onEvtThink
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Warrior of Ancient Times(20971)[268479590] - onEvtThink() for AI_INTENTION_ATTACK failed!
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1140)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1295)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:283)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onIntentionAttack(L2AttackableAI.java:431)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtAttacked(L2AttackableAI.java:2603)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:348)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:327)
	at com.l2jserver.gameserver.model.actor.L2Character.onHitTimer(L2Character.java:4938)
	at com.l2jserver.gameserver.model.actor.tasks.character.HitTask.run(HitTask.java:60)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
ene 10, 2016 12:25:44 PM com.l2jserver.gameserver.ai.L2AttackableAI onEvtThink
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Shaman of Ancient Times(20972)[268601830] - onEvtThink() for AI_INTENTION_ATTACK failed!
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1140)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1295)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:283)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onIntentionAttack(L2AttackableAI.java:431)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtAttacked(L2AttackableAI.java:2603)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:348)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:327)
	at com.l2jserver.gameserver.model.actor.L2Character.onHitTimer(L2Character.java:4938)
	at com.l2jserver.gameserver.model.actor.tasks.character.HitTask.run(HitTask.java:60)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
ene 10, 2016 12:45:31 PM com.l2jserver.gameserver.ai.L2AttackableAI onEvtThink
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Shaman of Ancient Times(20972)[268605226] - onEvtThink() for AI_INTENTION_ATTACK failed!
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1140)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1295)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:283)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onIntentionAttack(L2AttackableAI.java:431)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtAttacked(L2AttackableAI.java:2603)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:348)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:327)
	at com.l2jserver.gameserver.model.actor.L2Character.onHitTimer(L2Character.java:4938)
	at com.l2jserver.gameserver.model.actor.tasks.character.HitTask.run(HitTask.java:60)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
ene 10, 2016 12:51:16 PM com.l2jserver.gameserver.ai.L2AttackableAI onEvtThink
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Past Creature(20967)[268605801] - onEvtThink() for AI_INTENTION_ATTACK failed!
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1140)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1295)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:283)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onIntentionAttack(L2AttackableAI.java:431)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtAttacked(L2AttackableAI.java:2603)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:348)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:327)
	at com.l2jserver.gameserver.model.actor.L2Character.onHitTimer(L2Character.java:4938)
	at com.l2jserver.gameserver.model.actor.tasks.character.HitTask.run(HitTask.java:60)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
ene 10, 2016 12:51:17 PM com.l2jserver.gameserver.ai.L2AttackableAI onEvtThink
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Past Creature(20967)[268605801] - onEvtThink() for AI_INTENTION_ATTACK failed!
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1140)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1295)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:283)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onIntentionAttack(L2AttackableAI.java:431)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtAttacked(L2AttackableAI.java:2603)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:348)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:327)
	at com.l2jserver.gameserver.model.actor.L2Character.onHitTimer(L2Character.java:4938)
	at com.l2jserver.gameserver.model.actor.tasks.character.HitTask.run(HitTask.java:60)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
## Continue happend !!! at the moment

**Comment by Zealar** [comment]
Fixed https://github.com/L2J/L2J_Server/commit/c1683a932cfb6021c51340482c3946dbf6f58492
