### ISSUE TITLE
Community Board Bug

### ISSUE THREAD

**Issue by chxikva** [L2J/L2J_Server#208]
One of l2jserver support gave me community board core\datapack code i've imported it and now errors in studio :D please help me :)
https://files.gitter.im/L2J/L2J_Server/3xEw/Untitled.jpg
[06/01 18:43:23] Exception processing bypass from player chxikva: _bbshome
java.lang.NullPointerException
at handlers.communityboard.HomeBoard.parseCommunityBoardCommand(HomeBoar
d.java:105)
at com.l2jserver.gameserver.handler.CommunityBoardHandler.handleParseCom
mand(CommunityBoardHandler.java:123)
at com.l2jserver.gameserver.network.clientpackets.RequestBypassToServer.
runImpl(RequestBypassToServer.java:173)
at com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket.run
(L2GameClientPacket.java:69)
at com.l2jserver.gameserver.network.L2GameClient.run(L2GameClient.java:1
134)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

**Comment by maneco2** [comment]
No problems, i use a long time normal and custom Community Board, close issue.

**Comment by Zealar** [comment]
Use forum for report custom stuff.
