### ISSUE TITLE
Could not store summon effect data: {}

### ISSUE THREAD

**Issue by ghost** [L2J/L2J_Server#212]
ene 09, 2016 5:28:16 PM com.l2jserver.gameserver.model.actor.instance.L2ServitorInstance storeEffect
GRAVE: Could not store summon effect data: {}
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '268552277-0-1407-22223-1' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.execute(PreparedStatementProxy.java:44)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.execute(HikariPreparedStatementProxy.java)
	at com.l2jserver.gameserver.model.actor.instance.L2ServitorInstance.storeEffect(L2ServitorInstance.java:287)
	at com.l2jserver.gameserver.model.actor.L2Summon.doDie(L2Summon.java:302)
	at com.l2jserver.gameserver.model.actor.instance.L2ServitorInstance.doDie(L2ServitorInstance.java:166)
	at com.l2jserver.gameserver.model.actor.status.CharStatus.reduceHp(CharStatus.java:181)
	at com.l2jserver.gameserver.model.actor.status.SummonStatus.reduceHp(SummonStatus.java:120)
	at com.l2jserver.gameserver.model.actor.L2Character.reduceCurrentHp(L2Character.java:6312)
	at com.l2jserver.gameserver.model.actor.L2Character.reduceCurrentHp(L2Character.java:6296)
	at com.l2jserver.gameserver.model.actor.L2Summon.reduceCurrentHp(L2Summon.java:820)
	at handlers.effecthandlers.HpDrain.onStart(HpDrain.java:105)
	at com.l2jserver.gameserver.model.skills.Skill.applyEffectScope(Skill.java:1316)
	at com.l2jserver.gameserver.model.skills.Skill.applyEffects(Skill.java:1407)
	at com.l2jserver.gameserver.model.skills.Skill.applyEffects(Skill.java:1339)
	at com.l2jserver.gameserver.model.skills.Skill.activateSkill(Skill.java:1547)
	at com.l2jserver.gameserver.model.skills.Skill.activateSkill(Skill.java:1470)
	at com.l2jserver.gameserver.model.actor.L2Character.callSkill(L2Character.java:5792)
	at com.l2jserver.gameserver.model.actor.L2Character.onMagicHitTimer(L2Character.java:5594)
	at com.l2jserver.gameserver.model.actor.tasks.character.MagicUseTask.run(MagicUseTask.java:66)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by valanths1990** [comment]
happens from time to time
