### ISSUE TITLE
Failed running: [C] 1F Action ; null java.lang.IllegalMonitorStateException

### ISSUE THREAD

**Issue by ghost** [L2J/L2J_Server#215]
ene 10, 2016 4:43:58 PM com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket run
GRAVE: Client: [Character: xx[xxx] - Account: xxx - IP: xxx.xxx.xx.xxx] - Failed running: [C] 1F Action ; null
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1140)
	at com.l2jserver.gameserver.model.actor.instance.L2PcInstance.doAttack(L2PcInstance.java:4615)
	at com.l2jserver.gameserver.ai.L2PlayerAI.thinkAttack(L2PlayerAI.java:249)
	at com.l2jserver.gameserver.ai.L2PlayerAI.onEvtThink(L2PlayerAI.java:344)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:302)
	at com.l2jserver.gameserver.ai.L2PlayableAI.onIntentionAttack(L2PlayableAI.java:81)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at handlers.actionhandlers.L2NpcAction.action(L2NpcAction.java:87)
	at com.l2jserver.gameserver.model.L2Object.onAction(L2Object.java:128)
	at com.l2jserver.gameserver.model.L2Object.onAction(L2Object.java:120)
	at com.l2jserver.gameserver.network.clientpackets.Action.runImpl(Action.java:150)
	at com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:69)
	at com.l2jserver.gameserver.network.L2GameClient.run(L2GameClient.java:1134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

ene 10, 2016 4:44:05 PM com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket run
GRAVE: Client: [Character: xxx[xxxx] - Account: xxx - IP: xxx.xxx.xx.xxx] - Failed running: [C] 1F Action ; null
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1140)
	at com.l2jserver.gameserver.model.actor.instance.L2PcInstance.doAttack(L2PcInstance.java:4615)
	at com.l2jserver.gameserver.ai.L2PlayerAI.thinkAttack(L2PlayerAI.java:249)
	at com.l2jserver.gameserver.ai.L2PlayerAI.onEvtThink(L2PlayerAI.java:344)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:302)
	at com.l2jserver.gameserver.ai.L2PlayableAI.onIntentionAttack(L2PlayableAI.java:81)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at handlers.actionhandlers.L2NpcAction.action(L2NpcAction.java:87)
	at com.l2jserver.gameserver.model.L2Object.onAction(L2Object.java:128)
	at com.l2jserver.gameserver.model.L2Object.onAction(L2Object.java:120)
	at com.l2jserver.gameserver.network.clientpackets.Action.runImpl(Action.java:150)
	at com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:69)
	at com.l2jserver.gameserver.network.L2GameClient.run(L2GameClient.java:1134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
ene 11, 2016 4:42:51 AM com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket run
GRAVE: Client: [Character: Tix[268557449] - Account: 50593956 - IP: 186.109.1.97] - Failed running: [C] 1F Action ; null
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.StampedLock.unlockWrite(Unknown Source)
	at com.l2jserver.gameserver.model.actor.L2Character.doAttack(L2Character.java:1140)
	at com.l2jserver.gameserver.model.actor.instance.L2PcInstance.doAttack(L2PcInstance.java:4615)
	at com.l2jserver.gameserver.ai.L2PlayerAI.thinkAttack(L2PlayerAI.java:249)
	at com.l2jserver.gameserver.ai.L2PlayerAI.onEvtThink(L2PlayerAI.java:344)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:345)
	at com.l2jserver.gameserver.ai.AbstractAI.notifyEvent(AbstractAI.java:316)
	at com.l2jserver.gameserver.ai.L2CharacterAI.onIntentionAttack(L2CharacterAI.java:302)
	at com.l2jserver.gameserver.ai.L2PlayableAI.onIntentionAttack(L2PlayableAI.java:81)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:282)
	at com.l2jserver.gameserver.ai.AbstractAI.setIntention(AbstractAI.java:257)
	at handlers.actionhandlers.L2NpcAction.action(L2NpcAction.java:87)
	at com.l2jserver.gameserver.model.L2Object.onAction(L2Object.java:128)
	at com.l2jserver.gameserver.model.L2Object.onAction(L2Object.java:120)
	at com.l2jserver.gameserver.network.clientpackets.Action.runImpl(Action.java:150)
	at com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:69)
	at com.l2jserver.gameserver.network.L2GameClient.run(L2GameClient.java:1134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Zealar** [comment]
Fixed https://github.com/L2J/L2J_Server/commit/c1683a932cfb6021c51340482c3946dbf6f58492
