### ISSUE TITLE
Failed reading: [C] 1B AddTradeItem ; null java.nio.BufferUnderflowException

### ISSUE THREAD

**Issue by ghost** [L2J/L2J_Server#216]
ene 11, 2016 2:35:07 AM com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket read
GRAVE: Client: [Character: xxx[xxx] - Account: xxx - IP: xxx.xxx.xxx.xx] - Failed reading: [C] 1B AddTradeItem ; null
java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Unknown Source)
	at java.nio.HeapByteBuffer.getInt(Unknown Source)
	at com.l2jserver.mmocore.ReceivablePacket.readD(ReceivablePacket.java:90)
	at com.l2jserver.gameserver.network.clientpackets.AddTradeItem.readImpl(AddTradeItem.java:45)
	at com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket.read(L2GameClientPacket.java:47)
	at com.l2jserver.mmocore.SelectorThread.parseClientPacket(SelectorThread.java:456)
	at com.l2jserver.mmocore.SelectorThread.tryReadPacket(SelectorThread.java:391)
	at com.l2jserver.mmocore.SelectorThread.readPacket(SelectorThread.java:315)
	at com.l2jserver.mmocore.SelectorThread.run(SelectorThread.java:184)

**Comment by Zealar** [comment]
That is MMOCore problem mean there is less bytes that is required. Maybe cause by bad internet connection some is lost guess will not happen again. Reopen if still see it and internet is fine.

**Comment by Sacrifice78** [comment]
:+1:
