### ISSUE TITLE
Failed running: [C] 23 RequestBypassToServer ; null java.lang.NullPointerException

### ISSUE THREAD

**Issue by ghost** [L2J/L2J_Server#217]
ene 11, 2016 1:20:30 PM com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket run
GRAVE: Client: [Character: xxx[xxx] - Account: xxx - IP: xxx.xxx.xxx.xxx] - Failed running: [C] 23 RequestBypassToServer ; null
java.lang.NullPointerException
	at java.util.LinkedList$ListItr.next(Unknown Source)
	at com.l2jserver.gameserver.model.actor.instance.L2PcInstance.validateHtmlAction(L2PcInstance.java:10872)
	at com.l2jserver.gameserver.model.actor.instance.L2PcInstance.validateHtmlAction(L2PcInstance.java:10903)
	at com.l2jserver.gameserver.network.clientpackets.RequestBypassToServer.runImpl(RequestBypassToServer.java:109)
	at com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:69)
	at com.l2jserver.gameserver.network.L2GameClient.run(L2GameClient.java:1134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
:+1:
