### ISSUE TITLE
Bug Spawn Castle Ambassador

### ISSUE THREAD

**Issue by morzingrath** [L2J/L2J_Server#220]
[12/01 13:42:51] Exception on onSpawn() in notifySpawn(): null
java.lang.NullPointerException
        at ai.npc.CastleAmbassador.CastleAmbassador.onSpawn(CastleAmbassador.java:162)
        at com.l2jserver.gameserver.model.quest.Quest.notifySpawn(Quest.java:518)
        at com.l2jserver.gameserver.model.quest.Quest.lambda$addSpawnId$58(Quest.java:1980)
        at com.l2jserver.gameserver.model.events.listeners.ConsumerEventListener.executeEvent(ConsumerEventListener.java:46)
        at com.l2jserver.gameserver.model.events.EventDispatcher.notifyToListeners(EventDispatcher.java:242)
        at com.l2jserver.gameserver.model.events.EventDispatcher.notifyEventToMultipleContainers(EventDispatcher.java:178)
        at com.l2jserver.gameserver.model.events.EventDispatcher.lambda$notifyEventAsync$229(EventDispatcher.java:121)
        at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

I've this bug on the master ...

**Comment by Sacrifice78** [comment]
Its a NPE
