### ISSUE TITLE
More NPE's

### ISSUE THREAD

**Issue by Sacrifice78** [L2J/L2J_Server#229]
ene 26, 2016 2:48:44 PM com.l2jserver.gameserver.model.actor.L2Npc$RandomAnimationTask run
GRAVE: There has been an error trying to perform a random animation for NPC L2MonsterInstance:Purgatory Serpent(21153)[268509518]!
java.lang.NullPointerException
	at com.l2jserver.gameserver.model.actor.L2Npc$RandomAnimationTask.run(L2Npc.java:251)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

ene 26, 2016 6:54:44 PM com.l2jserver.gameserver.ai.L2AttackableAI movementDisable
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Fledgling Lavasaurus(18800)[268545841] - failed executing movementDisable()!
java.lang.NullPointerException
	at com.l2jserver.gameserver.model.L2Object.calculateDistance(L2Object.java:905)
	at com.l2jserver.gameserver.ai.L2AttackableAI.movementDisable(L2AttackableAI.java:1805)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1239)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.L2AttackableAI.run(L2AttackableAI.java:140)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

ene 26, 2016 6:57:40 PM com.l2jserver.gameserver.ai.L2AttackableAI movementDisable
ADVERTENCIA: L2AttackableAI: Actor: L2MonsterInstance:Adult Lavasaurus(18801)[268546629] - failed executing movementDisable()!
java.lang.NullPointerException
	at com.l2jserver.gameserver.ai.L2AttackableAI.targetReconsider(L2AttackableAI.java:2303)
	at com.l2jserver.gameserver.ai.L2AttackableAI.movementDisable(L2AttackableAI.java:1972)
	at com.l2jserver.gameserver.ai.L2AttackableAI.thinkAttack(L2AttackableAI.java:1239)
	at com.l2jserver.gameserver.ai.L2AttackableAI.onEvtThink(L2AttackableAI.java:2545)
	at com.l2jserver.gameserver.ai.L2AttackableAI.run(L2AttackableAI.java:140)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
:+1:
