### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Sacrifice78** [L2J/L2J_Server#235]
ene 29, 2016 6:21:54 PM com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket run
GRAVE: Client: Failed running: [C] D0:4B RequestDispel ; null
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at com.l2jserver.gameserver.data.sql.impl.SummonEffectsTable.removeEffects(SummonEffectsTable.java:70)
	at com.l2jserver.gameserver.data.sql.impl.SummonEffectsTable.removePetEffects(SummonEffectsTable.java:153)
	at com.l2jserver.gameserver.model.actor.instance.L2PetInstance.stopSkillEffects(L2PetInstance.java:934)
	at com.l2jserver.gameserver.network.clientpackets.RequestDispel.runImpl(RequestDispel.java:83)
	at com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:69)
	at com.l2jserver.gameserver.network.L2GameClient.run(L2GameClient.java:1134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
:+1:
