### ISSUE TITLE
Duplicate items when try to save in db

### ISSUE THREAD

**Issue by valanths1990** [L2J/L2J_Server#244]
ERROR:Could not insert item Enria(4042)[268566895] into DB: Reason: Duplicate entry '268566895' for key 'PRIMARY'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '268566895' for key 'PRIMARY'

This is just one example if server is running for long time

if this happen players can lose items
so it seems critical

**Comment by u3games** [comment]
Confirm...

`[17/02 23:30:47] Could not insert item Varnish(1865)[268702553] into DB: Reason: Duplicate entry '268702553' for key 'PRIMARY'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '268702553' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.l2jserver.gameserver.model.items.instance.L2ItemInstance.insertIntoDb(L2ItemInstance.java:1699)
	at com.l2jserver.gameserver.model.items.instance.L2ItemInstance.updateDatabase(L2ItemInstance.java:1470)
	at com.l2jserver.gameserver.model.itemcontainer.ItemContainer.deleteMe(ItemContainer.java:599)
	at com.l2jserver.gameserver.model.actor.instance.L2PcInstance.cleanup(L2PcInstance.java:11507)
	at com.l2jserver.gameserver.model.actor.instance.L2PcInstance.deleteMe(L2PcInstance.java:11180)
	at com.l2jserver.gameserver.network.L2GameClient$CleanupTask.run(L2GameClient.java:916)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by Sacrifice78** [comment]
Yes, this bug is confirmed!. :+1:

**Comment by luksdlt92** [comment]
What do you mean with running for long time? One day? One week? One month?

**Comment by Sacrifice78** [comment]
Since one week can be... @luksdlt92.
@valanths1990 totally off course with you.
