### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Sacrifice78** [L2J/L2J_Server#261]
mar 18, 2016 6:54:14 PM com.l2jserver.gameserver.network.clientpackets.RequestBypassToServer runImpl
ADVERTENCIA: Exception processing bypass from player xxxx: npc_268474090_Quest
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at com.l2jserver.gameserver.model.actor.instance.L2VillageMasterInstance.onBypassFeedback(L2VillageMasterInstance.java:101)
	at com.l2jserver.gameserver.network.clientpackets.RequestBypassToServer.runImpl(RequestBypassToServer.java:197)
	at com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:69)
	at com.l2jserver.gameserver.network.L2GameClient.run(L2GameClient.java:1134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by MikeInfinity** [comment]
Yeah, this happens to me too when I click "Quest" on a village master :/

**Comment by Sacrifice78** [comment]
Then... CONFIRMED tag. :)

**Comment by Sacrifice78** [comment]
Thank you monster... :+1:
