### ISSUE TITLE
[Dev][H5][Priority 1] The server does not start.

### ISSUE THREAD

**Issue by gajet5** [L2J/L2J_Server#271]
`[31/03 16:34:02] Could not update characters online status: Table 'l2jgs.characters' doesn't exist
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'l2jgs.characters' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2546)
        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1541)
        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2605)
        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1469)
        at com.zaxxer.hikari.proxy.StatementProxy.executeUpdate(StatementProxy.java:119)
        at com.zaxxer.hikari.proxy.HikariStatementProxy.executeUpdate(HikariStatementProxy.java)
        at com.l2jserver.gameserver.idfactory.IdFactory.setAllCharacterOffline(IdFactory.java:180)
        at com.l2jserver.gameserver.idfactory.IdFactory.<init>(IdFactory.java:140)
        at com.l2jserver.gameserver.idfactory.BitSetIDFactory.<init>(BitSetIDFactory.java:54)
        at com.l2jserver.gameserver.idfactory.IdFactory.<clinit>(IdFactory.java:161)
        at com.l2jserver.gameserver.GameServer.<init>(GameServer.java:165)
        at com.l2jserver.gameserver.GameServer.main(GameServer.java:458)

[31/03 16:34:02] Could not clean up database: Table 'l2jgs.account_gsdata' doesn't exist
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'l2jgs.account_gsdata' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2546)
        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1541)
        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2605)
        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1469)
        at com.zaxxer.hikari.proxy.StatementProxy.executeUpdate(StatementProxy.java:119)
        at com.zaxxer.hikari.proxy.HikariStatementProxy.executeUpdate(HikariStatementProxy.java)
        at com.l2jserver.gameserver.idfactory.IdFactory.cleanUpDB(IdFactory.java:223)
        at com.l2jserver.gameserver.idfactory.IdFactory.<init>(IdFactory.java:147)
        at com.l2jserver.gameserver.idfactory.BitSetIDFactory.<init>(BitSetIDFactory.java:54)
        at com.l2jserver.gameserver.idfactory.IdFactory.<clinit>(IdFactory.java:161)
        at com.l2jserver.gameserver.GameServer.<init>(GameServer.java:165)
        at com.l2jserver.gameserver.GameServer.main(GameServer.java:458)

[31/03 16:34:02] BitSetIDFactory: Could not be initialized properly: Table 'l2jgs.characters' doesn't exist
[31/03 16:34:02] BitSetIDFactory: 102912 id's available.
[31/03 16:34:02] GameServer: Could not read object IDs from database. Please check your configuration.
Exception in thread "main" java.lang.Exception: Could not initialize the ID factory!
        at com.l2jserver.gameserver.GameServer.<init>(GameServer.java:168)
        at com.l2jserver.gameserver.GameServer.main(GameServer.java:458)
`

**Comment by gajet5** [comment]
I checked on the second bench.
The server starts, the only problem I have.
